sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: sk+mbn60eTbi4vz+JHAm58jXk0C8zgVrmTZuaUp5E2ACHEbv8qv4rgiPH1uK7nefmVX+62mU53z2TuEcPEI9Y0aJspAdBWkMbvVl4hW5UfHaRydnQ2F1PwlfWytprW4rHO5o8ljWYSUnripRfTi5oJSgWj9Q4rLG+NDhZZYq7yuF5Or1adLeX1Gnj4sECbsD17KnGUCDNEVN65bLrTrCq/PHdRVk6uc9uaEPxAb/Q6gClwPmfDlwvhupxKYLLSJctfEFMUrJGCdc7QP5LdEVLdqVaLbH1t31gDjfBpQ/BTCnhnc10GY99NsahXk882jL9wu3Cw9dp74Qeyi+LJ+W79SQKdglGmrDZWYk9FTrie5ZiYDf2vnt3qRoePQxE65jUO/pLGJGErTktMmOHDS+yE0i+BiXmRE22wUNYOEtLKwUxnkEdZP1nOfS6IyXBwV6t8qeJAbYlCxe5f2vzzcAgOdpTJen1w0kwBiHZ0Fdh+3UpFvF3o/uhOmBa3m2j/K4zKu5C7AL3AleTF/c2YP127irXEfPiywrle3VNaj2lykDW6I9dGXfzesMr7G6vWEP3phxlOz/HFMifysSglrk5Eld2dagI+rgLnzBEWZ0r+NOl0rktDtmUAnn8cHPlRYDexD/4EmRH9/0k+0iRBDMEUmE7W4v/Bq1rLsKnZSmZHo=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: pCB5zGshZgcFYR5Z5Q8kjKQJIvGgrtCbbZckcuoFMSMJo5YJQ/j/zf6k+kboQkiZv9dIzJz00AzIobODo3+y7e6JVQsXO19E/D3zc3GtAo3b/Ixt7Rc+IByjsdCZmvFfwL2EjK+ChsEd9zANds4TGFl7AXGhyauBlvVSN5iu50f/sNpZUqYqJsgXnsPnX54HxHYmKFOjlt2ZaUZl70En7TjfeTX95Wasb4ILGafaunbj/vnd1t0Rw+zJwJ0bFL4lPGR/bOhJlXbvv/2kXwCWqt7TiSJH09v8LBy/u4lWnXjMVVUO58w0EKou3r7KPp7jnCxwg/rrXUZws4gvL9IUUcf6/lbJwDWYX8mdPQvrR5+Ku6XlaHieClYD28Gwknx0y5Gm3sVMJCxW7W6LCCRxKmJq4EZW6oSVKAkAx2leZRD+YTLYC9j8YER7T8COglSee5e22AIEBy9OegbShyK+EOMOuLRoc/asLAyNdIzBZtiCcR6isp8xtDS7Py6adFvFzvbkiLBfXXTbhaCiSj1qRtp+M6Ff/n2te8+W/I93ITYem1cjJu/FFeVrvhOnnkwq40YCzN/Wn9xzRdKJPauKvp0x2StFsYxQY1hZqhKw6kq88Os8DxYSFBb0VQxpGFNqvOLGeBxGT3+TM1mfs0ApwbJwthnYJvumRcZqe2Ss3Rs=
